# -*- coding: utf-8 -*-
"""Q3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6yTB73PD5YfaNaDu5eQpGXhMOQ0v__y
"""

!pip install astroquery photutils astropy scikit-learn

import pandas as pd
import numpy as np
from astroquery.sdss import SDSS
from astropy import coordinates as coords
from astropy import units
from astropy.io import fits
from photutils.aperture import aperture_photometry, CircularAperture
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

# Suppress RuntimeWarnings from numpy, specifically for log10 of invalid values
np.seterr(divide='ignore', invalid='ignore')

def flux_to_mag(flux, F0=3631):
    return -2.5 * np.log10(flux / F0)

aperture = CircularAperture([(50, 50)], r=10)

# Define multiple RA/Dec positions to query (each patch ≤3 arcmin)
positions = [
    coords.SkyCoord(180, 0, unit="deg"),
    coords.SkyCoord(181, 0.5, unit="deg"),
    coords.SkyCoord(182, -0.5, unit="deg"),
    coords.SkyCoord(183, 1, unit="deg"),
    coords.SkyCoord(184, -1, unit="deg")
]

all_galaxy_features = []

for pos in positions:
    xid = SDSS.query_region(pos, spectro=True, radius=3*units.arcmin)
    if xid is None:
        continue

    images_g = SDSS.get_images(matches=xid, band='g')
    images_r = SDSS.get_images(matches=xid, band='r')
    images_i = SDSS.get_images(matches=xid, band='i')

    for i in range(len(xid)):
        try:
            redshift = xid['z'][i]
            if np.isnan(redshift):
                continue

            fluxes = {}
            for band, images in zip(['g','r','i'], [images_g, images_r, images_i]):
                if i < len(images) and images[i] is not None:
                    fluxes[band] = aperture_photometry(images[i][0].data, aperture)['aperture_sum'][0]
                else:
                    fluxes[band] = None

            features = {"size": 5.0, "ellipticity": 0.3, "redshift": redshift}

            if fluxes['r'] is not None:
                features["brightness"] = fluxes['r']
            if fluxes['g'] is not None and fluxes['r'] is not None:
                features["g_r"] = flux_to_mag(fluxes['g']) - flux_to_mag(fluxes['r'])
            if fluxes['r'] is not None and fluxes['i'] is not None:
                features["r_i"] = flux_to_mag(fluxes['r']) - flux_to_mag(fluxes['i'])

            if len(features) > 3:
                all_galaxy_features.append(features)

        except Exception as e:
            print(f"Skipped galaxy {i} due to error: {e}")

df = pd.DataFrame(all_galaxy_features)

if df.empty:
    print("No galaxy features were successfully extracted. DataFrame is empty. Cannot train model.")
else:
    print(f"Collected {len(df)} galaxies for training.")

    # Select only the features that are available for both training and single-image prediction
    # The 'g_r' and 'r_i' features are not available for a single uploaded FITS image.
    features_for_training = [col for col in df.columns if col not in ['redshift', 'g_r', 'r_i']]
    X = df[features_for_training]
    y = df["redshift"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    print("Training metrics:")
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("R²:", r2_score(y_test, y_pred))

    from google.colab import files
    uploaded = files.upload()

    image_data = fits.getdata(list(uploaded.keys())[0])
    phot_table = aperture_photometry(image_data, aperture)
    flux_r = phot_table['aperture_sum'][0]

    # Ensure the order of features matches the training data
    new_features = pd.DataFrame([
        {
            "size": 5.0,
            "ellipticity": 0.3,
            "brightness": flux_r
        }
    ])

    predicted_z = model.predict(new_features)[0]
    print("Predicted redshift for uploaded galaxy:", predicted_z)